import { assembly, loop, or } from './assembly';
import createNodes from './create-nodes';
import eventStore from './events/event-store';
import arrayFrom from './polyfills/array-from';

arrayFrom();

window.a = assembly('A');
window.abbr = assembly('ABBR');
window.address = assembly('ADDRESS');
window.area = assembly('AREA');
window.article = assembly('ARTICLE');
window.aside = assembly('ASIDE');
window.audio = assembly('audio');
window.b = assembly('B');
window.base = assembly('base');
window.bdi = assembly('bdi');
window.bdo = assembly('bdo');
window.blockquote = assembly('blockquote');
window.body = assembly('body');
window.br = assembly('BR');
window.button = assembly('button');
window.canvas = assembly('canvas');
window.caption = assembly('caption');
window.cite = assembly('cite');
window.code = assembly('code');
window.col = assembly('col');
window.colgroup = assembly('colgroup');
window.command = assembly('command');
window.dd = assembly('dd');
window.del = assembly('del');
window.dfn = assembly('dfn');
window.div = assembly('DIV');
window.dl = assembly('dl');
window.doctype = assembly('doctype');
window.dt = assembly('dt');
window.em = assembly('em');
window.embed = assembly('embed');
window.fieldset = assembly('fieldset');
window.figcaption = assembly('figcaption');
window.figure = assembly('figure');
window.footer = assembly('footer');
window.form = assembly('form');
window.h1 = assembly('H1');
window.h2 = assembly('H2');
window.h3 = assembly('H3');
window.h4 = assembly('H4');
window.h5 = assembly('H5');
window.h6 = assembly('H6');
window.header = assembly('header');
window.hgroup = assembly('hgroup');
window.hr = assembly('HR');
window.html = assembly('HTML');
window.i = assembly('I');
window.iframe = assembly('iframe');
window.img = assembly('IMG');
window.input = assembly('input');
window.ins = assembly('ins');
window.kbd = assembly('kbd');
window.keygen = assembly('keygen');
window.label = assembly('label');
window.legend = assembly('legend');
window.li = assembly('LI');
window.link = assembly('link');
window.map = assembly('map');
window.mark = assembly('mark');
window.menu = assembly('menu');
window.meta = assembly('meta');
window.nav = assembly('NAV');
window.noscript = assembly('noscript');
window.object = assembly('object');
window.ol = assembly('ol');
window.optgroup = assembly('optgroup');
window.option = assembly('option');
window.p = assembly('P');
window.param = assembly('param');
window.pre = assembly('pre');
window.progress = assembly('progress');
window.q = assembly('q');
window.rp = assembly('rp');
window.rt = assembly('rt');
window.ruby = assembly('ruby');
window.s = assembly('s');
window.samp = assembly('samp');
window.script = assembly('script');
window.section = assembly('SECTION');
window.select = assembly('select');
window.small = assembly('small');
window.source = assembly('source');
window.span = assembly('SPAN');
window.strong = assembly('strong');
window.style = assembly('style');
window.sub = assembly('sub');
window.sup = assembly('sup');
window.table = assembly('table');
window.tbody = assembly('tbody');
window.td = assembly('td');
window.textarea = assembly('textarea');
window.tfoot = assembly('tfoot');
window.th = assembly('th');
window.thead = assembly('thead');
window.title = assembly('title');
window.tr = assembly('tr');
window.ul = assembly('UL');
window.v = assembly('var');
window.video = assembly('video');


// Create API
window.createNodes = createNodes;
window.loop = loop;
window.or = or;
window.eventStore = eventStore;

 